# Generated by Django 5.2.4 on 2025-07-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('calendar_id', models.CharField(blank=True, max_length=50, null=True)),
                ('location_id', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
