# Generated by Django 5.2.4 on 2025-07-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_auth', '0002_ghluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghluser',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
    ]
