# Generated by Django 5.2.4 on 2025-07-18 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_auth', '0003_ghluser_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_other_employees', models.IntegerField(help_text='0 means working alone')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ghl_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='ghl_auth.ghluser')),
            ],
            options={
                'unique_together': {('ghl_user', 'num_other_employees')},
            },
        ),
    ]
