# Generated by Django 5.2.4 on 2025-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_auth', '0004_commissionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghluser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ghluser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ghluser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ghluser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ghluser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
