# Generated by Django 5.2.4 on 2025-07-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_assigned_to_job_location_id_job_monetary_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
