# Generated by Django 5.2.4 on 2025-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payout_userpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='opportunity_id',
            field=models.CharField(max_length=100),
        ),
    ]
