# Generated by Django 5.2.4 on 2025-07-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_payout_opportunity_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPercentage',
        ),
    ]
