# Generated by Django 5.2.4 on 2025-07-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_userpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='opportunity_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
