# Generated by Django 5.2.4 on 2025-12-09 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_payout_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ghl_invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('contact_id', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('contact_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_logo_url', models.URLField(blank=True, null=True)),
                ('location_id', models.CharField(max_length=100)),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('live_mode', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='api_invoice_token_fc73e8_idx'), models.Index(fields=['ghl_invoice_id'], name='api_invoice_ghl_inv_49662c_idx'), models.Index(fields=['invoice_number'], name='api_invoice_invoice_59a3b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('taxes', models.JSONField(blank=True, default=list)),
                ('ghl_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
