# Generated by Django 5.2.4 on 2025-12-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invoice_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
