# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_invoice_signature_invoice_signed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
