# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_invoice_discount_value_invoice_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
