# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_invoice_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tip_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tip_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
